spring.datasource.url=jdbc:postgresql://localhost:5432/madelaPractice
spring.datasource.username=postgres
spring.datasource.password=2710
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tryItOutEnabled=true

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

spring.jpa.properties.javax.persistence.validation.mode=auto